package com.qz.fvideo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qz.fvideo.bean.ExtraBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig extraBeanDaoConfig;

    private final ExtraBeanDao extraBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        extraBeanDaoConfig = daoConfigMap.get(ExtraBeanDao.class).clone();
        extraBeanDaoConfig.initIdentityScope(type);

        extraBeanDao = new ExtraBeanDao(extraBeanDaoConfig, this);

        registerDao(ExtraBean.class, extraBeanDao);
    }
    
    public void clear() {
        extraBeanDaoConfig.clearIdentityScope();
    }

    public ExtraBeanDao getExtraBeanDao() {
        return extraBeanDao;
    }

}
